# Generated by Django 4.1.5 on 2023-02-05 07:12

from django.db import migrations, models
import puzzle_editing.models


class Migration(migrations.Migration):
    dependencies = [
        ("puzzle_editing", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="puzzle",
            name="codename",
            field=models.CharField(
                default=puzzle_editing.models.generate_codename,
                help_text=(
                    "A non-spoilery name. Feel free to use the autogenerated one."
                ),
                max_length=500,
            ),
        ),
    ]
