# Generated by Django 3.1.13 on 2024-01-19 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_editing', '0002_mh2023_changes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='canonical_puzzle',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='deep',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='deep_key',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='discord_emoji',
        ),
    ]
