# Generated by Django 4.1.5 on 2023-02-08 02:30

from django.db import migrations
import puzzle_editing.models


class Migration(migrations.Migration):
    dependencies = [
        ("puzzle_editing", "0003_alter_puzzle_codename"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", puzzle_editing.models.PuzzupUserManager()),
            ],
        ),
    ]
