# Generated by Django 3.1.13 on 2024-01-25 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_editing', '0003_mh2025_drop_deep_emoji'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puzzle',
            options={'permissions': [('list_puzzle', 'Can see all puzzles'), ('unspoil_puzzle', 'Can unspoil people')]},
        ),
    ]
