# Generated by Django 3.1.13 on 2024-01-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_editing', '0004_mk2025_add_puzzle_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hint',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='pseudoanswer',
            options={'ordering': ('puzzle', 'answer')},
        ),
        migrations.AlterModelOptions(
            name='puzzle',
            options={'permissions': (('list_puzzle', 'Can see all puzzles'), ('unspoil_puzzle', 'Can unspoil people'))},
        ),
        migrations.AlterField(
            model_name='puzzlepostprod',
            name='host_url',
            field=models.CharField(blank=True, default='', help_text='The base URL where this puzzle is postprodded. Defaults to staging', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='round',
            name='puzzle_template',
            field=models.CharField(blank=True, default='', help_text='Path to puzzle template in the hunt repo for autopostprod', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='round',
            name='solution_template',
            field=models.CharField(blank=True, default='', help_text='Path to sol template in the hunt repo for autopostprod', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testsolveparticipation',
            name='aspects_accessibility',
            field=models.TextField(blank=True, default='', help_text='If you have physical issues such as a hearing impairment, vestibular disorder, etc., what problems did you encounter with this puzzle, if any?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testsolveparticipation',
            name='aspects_enjoyable',
            field=models.TextField(blank=True, default='', help_text='What parts of the puzzle were particularly enjoyable, if any?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testsolveparticipation',
            name='aspects_unenjoyable',
            field=models.TextField(blank=True, default='', help_text='What parts of the puzzle were not enjoyable, if any?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testsolveparticipation',
            name='clues_needed',
            field=models.TextField(blank=True, default='', help_text='Did you solve the complete puzzle before getting the answer, or did you shortcut, and if so, how much remained unsolved?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testsolveparticipation',
            name='errors_found',
            field=models.TextField(blank=True, default='', help_text='What errors, if any, did you notice in the puzzle?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testsolveparticipation',
            name='flavortext_feedback',
            field=models.TextField(blank=True, default='', help_text='**If Helpful:** How did the flavor text help?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testsolveparticipation',
            name='flavortext_overall',
            field=models.CharField(choices=[('helpful', 'It was helpful and appropriate'), ('too_leading', 'It was too leading'), ('not_helpful', 'It was not helpful'), ('confused', 'It confused us, or led us in a wrong direction'), ('none_but_ok', 'There was no flavor text, and that was fine'), ('none_not_ok', 'There was no flavor text, and I would have liked some')], default='', help_text='Which best describes the flavor text?', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testsolveparticipation',
            name='general_feedback',
            field=models.TextField(blank=True, default='', help_text='What did you like & dislike about this puzzle? Is there anything you think should be changed (e.g. amount of flavor/cluing, errata, tech issues, mechanics, theming, etc.)?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testsolveparticipation',
            name='instructions_feedback',
            field=models.TextField(blank=True, default='', help_text='**If No:** What was confusing about the instructions?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testsolveparticipation',
            name='instructions_overall',
            field=models.BooleanField(default=True, help_text='Were the instructions clear?'),
        ),
        migrations.AlterField(
            model_name='testsolveparticipation',
            name='misc_feedback',
            field=models.TextField(blank=True, default='', help_text='Anything else you want to add? If you were spoiled, mention it here. (This can include: things you tried, any shortcuts you found, break-ins, stuck points, accessibility)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testsolveparticipation',
            name='stuck_points',
            field=models.TextField(blank=True, default='', help_text='**If Yes:** Where did you get stuck? List as many places as relevant.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testsolveparticipation',
            name='stuck_unstuck',
            field=models.TextField(blank=True, default='', help_text='**If Yes:** What helped you get unstuck? Was it a satisfying aha?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testsolveparticipation',
            name='suggestions_change',
            field=models.TextField(blank=True, default='', help_text='Do you have suggestions to change the puzzle? Please explain why your suggestion(s) will help.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testsolveparticipation',
            name='suggestions_keep',
            field=models.TextField(blank=True, default='', help_text='Do you have suggestions for things that should definitely stay in the puzzle? Please explain what you like about them.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testsolveparticipation',
            name='technical_issues_description',
            field=models.TextField(blank=True, default='', help_text='**If Yes:** Please describe the issue'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testsolveparticipation',
            name='technical_issues_device',
            field=models.TextField(blank=True, default='', help_text='**If Yes:** What type of device was the issue associated with? Please be as specific as possible (PC vs Mac, what browser, etc'),
            preserve_default=False,
        ),
    ]
