# Generated by Django 4.1.5 on 2023-02-08 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("puzzle_editing", "0004_alter_user_options_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="testsolvesession",
            name="admin",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="testsolve_admin_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
