# Generated by Django 4.1.5 on 2023-02-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("puzzle_editing", "0005_testsolvesession_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="testsolvesession",
            name="discord_thread_id",
            field=models.CharField(blank=True, max_length=19),
        ),
        migrations.AddField(
            model_name="testsolvesession",
            name="google_sheets_id",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
