# Generated by Django 4.2.9 on 2024-01-27 02:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("puzzle_editing", "0005_lint_fixups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="round",
            name="act",
        ),
        migrations.DeleteModel(
            name="Act",
        ),
    ]
