# Generated by Django 4.1.5 on 2023-02-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("puzzle_editing", "0006_testsolvesession_discord_thread_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testsolvesession",
            name="admin_thread_id",
            field=models.CharField(blank=True, max_length=19),
        ),
    ]
