# Generated by Django 4.2.9 on 2024-01-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("puzzle_editing", "0006_remove_act"),
    ]

    operations = [
        migrations.AlterField(
            model_name="puzzlecredit",
            name="credit_type",
            field=models.CharField(
                choices=[("ART", "Art"), ("TCH", "Tech"), ("OTH", "Other")],
                default="ART",
                max_length=3,
            ),
        ),
    ]
