# Generated by Django 4.2.9 on 2024-01-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("puzzle_editing", "0007_fix_puzzle_credit_type_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="timezone",
            field=models.CharField(
                blank=True, help_text="Your timezone, e.g. US/Eastern", max_length=100
            ),
        ),
    ]
