# Generated by Django 4.1.5 on 2023-02-10 06:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("puzzle_editing", "0007_testsolvesession_admin_thread_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="display_name",
        ),
    ]
