# Generated by Django 4.1.5 on 2023-02-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("puzzle_editing", "0008_remove_user_display_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testsolveparticipation",
            name="flavortext_overall",
            field=models.CharField(
                blank=True,
                choices=[
                    ("helpful", "It was helpful and appropriate"),
                    ("too_leading", "It was too leading"),
                    ("not_helpful", "It was not helpful"),
                    ("confused", "It confused us, or led us in a wrong direction"),
                    ("none_but_ok", "There was no flavor text, and that was fine"),
                    (
                        "none_not_ok",
                        "There was no flavor text, and I would have liked some",
                    ),
                ],
                help_text="Which best describes the flavor text?",
                max_length=20,
                null=True,
            ),
        ),
    ]
