# Generated by Django 4.2.9 on 2024-01-28 22:45

from django.db import migrations, models
import puzzle_editing.models


class Migration(migrations.Migration):
    dependencies = [
        ("puzzle_editing", "0008_user_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, unique=True, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./#/+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[puzzle_editing.models.CustomUsernameValidator()],
                verbose_name="username",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="puzzle_edit_email_1d9a5d_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["discord_user_id"], name="puzzle_edit_discord_106f26_idx"
            ),
        ),
    ]
