# Generated by Django 4.1.5 on 2023-02-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("puzzle_editing", "0010_testsolveparticipation_general_feedback_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testsolvesession",
            name="is_open",
            field=models.BooleanField(default=True),
        ),
    ]
