# Generated by Django 4.2.9 on 2024-01-28 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("puzzle_editing", "0010_non_unique_emails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="discord_user_id",
            field=models.CharField(blank=True, max_length=500, unique=True),
        ),
    ]
