# Generated by Django 4.2.9 on 2024-01-29 06:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("puzzle_editing", "0011_unique_discord_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="avatar_url",
        ),
    ]
