# Generated by Django 5.0.1 on 2024-01-31 22:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("puzzle_editing", "0012_remove_discord_avatar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="puzzle",
            options={
                "permissions": (
                    ("list_puzzle", "Can see all puzzles"),
                    ("unspoil_puzzle", "Can unspoil people"),
                    ("change_status_puzzle", "Can change puzzle status"),
                )
            },
        ),
    ]
