# Generated by Django 4.1.7 on 2023-02-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "puzzle_editing",
            "0012_alter_testsolveparticipation_general_feedback_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="puzzleanswer",
            name="case_sensitive",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Whether or not this answer needs to be submitted with the correct"
                    " casing."
                ),
            ),
        ),
        migrations.AddField(
            model_name="puzzleanswer",
            name="whitespace_sensitive",
            field=models.BooleanField(
                default=False,
                help_text="Whether or not this answer shouldn't ignore whitespaces.",
            ),
        ),
    ]
