# Generated by Django 5.0.1 on 2024-02-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("puzzle_editing", "0013_add_status_change_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="puzzle",
            name="logistics_clean_testsolve_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
