# Generated by Django 5.0.1 on 2024-02-02 20:21

from django.db import migrations, models

from puzzle_editing import status


REMOVED_STATUSES = [
    "AE",
    "ND",
    "WR",
    "AR",
    "AT",
    "TR",
    "R",
    "RP",
    "AO",
    "SS",
    "AS",
    "PP",
    "PB",
    "BT",
    "NC",
    "NA",
]


def remove_deprecated_statuses(apps, _schema_editor):
    Puzzle = apps.get_model("puzzle_editing", "Puzzle")
    Puzzle.objects.filter(status__in=REMOVED_STATUSES).update(status=status.INITIAL_IDEA)
    PuzzleComment = apps.get_model("puzzle_editing", "PuzzleComment")
    PuzzleComment.objects.filter(status_change__in=REMOVED_STATUSES).update(status_change=status.INITIAL_IDEA)
    StatusSubscription = apps.get_model("puzzle_editing", "StatusSubscription")
    StatusSubscription.objects.filter(status__in=REMOVED_STATUSES).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("puzzle_editing", "0014_clean_testsolve_count"),
    ]

    operations = [
        migrations.RunPython(remove_deprecated_statuses, lambda _apps, _schema_editor: None),
        migrations.AlterField(
            model_name="puzzle",
            name="status",
            field=models.CharField(
                choices=[
                    ("II", "Initial Idea"),
                    ("ID", "In Development"),
                    ("AA", "Waiting for Answer"),
                    ("W", "Writing / Revising (Answer Assigned)"),
                    ("WF", "Writing / Revising (Answer Flexible)"),
                    ("T", "In Testsolving"),
                    ("NS", "Finalizing Solution"),
                    ("AF", "Puzzle Written, Waiting for Round"),
                    ("NP", "Ready for Postprodding"),
                    ("AP", "Awaiting Approval After Postprod"),
                    ("NF", "Factchecking"),
                    ("NR", "Final Revisions"),
                    ("NK", "Needs Final Day Factcheck"),
                    ("D", "Done"),
                    ("DF", "Deferred"),
                    ("X", "Dead"),
                ],
                default="II",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="puzzlecomment",
            name="status_change",
            field=models.CharField(
                blank=True,
                choices=[
                    ("II", "Initial Idea"),
                    ("ID", "In Development"),
                    ("AA", "Waiting for Answer"),
                    ("W", "Writing / Revising (Answer Assigned)"),
                    ("WF", "Writing / Revising (Answer Flexible)"),
                    ("T", "In Testsolving"),
                    ("NS", "Finalizing Solution"),
                    ("AF", "Puzzle Written, Waiting for Round"),
                    ("NP", "Ready for Postprodding"),
                    ("AP", "Awaiting Approval After Postprod"),
                    ("NF", "Factchecking"),
                    ("NR", "Final Revisions"),
                    ("NK", "Needs Final Day Factcheck"),
                    ("D", "Done"),
                    ("DF", "Deferred"),
                    ("X", "Dead"),
                ],
                help_text="Any status change caused by this comment. Only used for recording history and computing statistics; not a source of truth (i.e. the puzzle will still store its current status, and this field's value on any comment doesn't directly imply anything about that in any technically enforced way).",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="statussubscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("II", "Initial Idea"),
                    ("ID", "In Development"),
                    ("AA", "Waiting for Answer"),
                    ("W", "Writing / Revising (Answer Assigned)"),
                    ("WF", "Writing / Revising (Answer Flexible)"),
                    ("T", "In Testsolving"),
                    ("NS", "Finalizing Solution"),
                    ("AF", "Puzzle Written, Waiting for Round"),
                    ("NP", "Ready for Postprodding"),
                    ("AP", "Awaiting Approval After Postprod"),
                    ("NF", "Factchecking"),
                    ("NR", "Final Revisions"),
                    ("NK", "Needs Final Day Factcheck"),
                    ("D", "Done"),
                    ("DF", "Deferred"),
                    ("X", "Dead"),
                ],
                max_length=2,
            ),
        ),
    ]
