# Generated by Django 5.0.1 on 2024-02-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("puzzle_editing", "0015_simplify_statuses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="puzzle",
            name="content",
        ),
        migrations.RemoveField(
            model_name="puzzle",
            name="solution",
        ),
        migrations.AddField(
            model_name="puzzle",
            name="content_google_doc_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="puzzle",
            name="resource_google_folder_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="puzzle",
            name="solution_google_doc_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="testsolvesession",
            name="puzzle_copy_google_doc_id",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
