# Generated by Django 4.1.7 on 2023-03-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("puzzle_editing", "0015_testsolveparticipation_solve_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testsolveparticipation",
            name="solve_path",
            field=models.TextField(
                blank=True,
                help_text="**Solve path**. What was the path you used to solve?",
                null=True,
            ),
        ),
    ]
