# Generated by Django 5.0.1 on 2024-02-03 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("puzzle_editing", "0016_puzzle_content_as_google_docs"),
    ]

    operations = [
        migrations.AddField(
            model_name="puzzle",
            name="logistics_needs_final_day_factcheck",
            field=models.BooleanField(
                default=False,
                help_text="Are any facts or statuses of things outside the puzzle used in the puzzle that could possibly change before hunt, e.g. the ice cream flavors available at a certain store, or content on an external webpage? If so, factchecking will do a final day check.",
                verbose_name="Needs final day factcheck",
            ),
        ),
    ]
