# Generated by Django 5.0.1 on 2024-02-03 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzle_editing", "0017_logistics_factcheck_external_sources"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordCategoryCache",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("position", models.IntegerField()),
                ("puzzle_status", models.CharField(blank=True, max_length=2)),
                ("puzzle_status_index", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DiscordTextChannelCache",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("topic", models.CharField(max_length=100)),
                ("position", models.IntegerField()),
                ("permission_overwrites", models.JSONField()),
                (
                    "category",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="text_channels",
                        to="puzzle_editing.discordcategorycache",
                    ),
                ),
            ],
        ),
    ]
