# Generated by Django 4.1.7 on 2023-03-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("puzzle_editing", "0017_alter_puzzlecredit_credit_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testsolvesession",
            name="admin_thread_id",
        ),
        migrations.AddField(
            model_name="puzzle",
            name="testsolving_admin_thread_id",
            field=models.CharField(blank=True, max_length=19),
        ),
    ]
