# Generated by Django 5.0.2 on 2024-02-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzle_editing", "0019_ops_support_requests"),
    ]

    operations = [
        migrations.AddField(
            model_name="statussubscription",
            name="meta_filter",
            field=models.CharField(
                choices=[("A", "All"), ("M", "Meta Only"), ("N", "Non-Meta Only")],
                default="A",
                max_length=1,
            ),
        ),
    ]
