# Generated by Django 5.0.2 on 2024-02-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzle_editing", "0020_meta_only_status_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="puzzle",
            name="discord_info_message_id",
            field=models.CharField(blank=True, max_length=19),
        ),
    ]
