# Generated by Django 4.2.1 on 2023-05-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "puzzle_editing",
            "0020_puzzle_discussion_editors_alter_puzzle_status_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="testsolvesession",
            name="discord_vc_id",
            field=models.CharField(blank=True, max_length=19),
        ),
    ]
