# Generated by Django 5.0.2 on 2024-02-15 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzle_editing", "0021_discord_info_message_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="puzzle",
            name="private_notes",
            field=models.TextField(
                blank=True,
                help_text="Private notes about this puzzle, visible only to the EICs",
                verbose_name="Private notes",
            ),
        ),
    ]
