# Generated by Django 4.2.1 on 2023-05-23 03:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("puzzle_editing", "0022_alter_puzzle_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="puzzleanswer",
            name="special_sensitive",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Whether or not this answer shouldn't ignore special characters."
                ),
            ),
        ),
    ]
