# Generated by Django 5.0.2 on 2024-03-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzle_editing", "0023_add_file_uploads"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discordtextchannelcache",
            name="topic",
            field=models.CharField(max_length=1024),
        ),
    ]
