# Generated by Django 5.0.2 on 2024-03-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzle_editing", "0024_discord_topic_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="puzzle",
            name="logistics_closed_testsolving",
            field=models.BooleanField(
                default=False,
                help_text="Check this box if this puzzle should only allow testsolve sessions created by a testsolve coordinator",
            ),
        ),
    ]
