# Generated by Django 4.2.1 on 2023-06-08 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("puzzle_editing", "0024_testsolvefeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="testsolveguess",
            name="partial_response",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="testsolveguess",
            name="partially_correct",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="PseudoAnswer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.TextField(max_length=100)),
                ("response", models.TextField()),
                (
                    "puzzle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pseudo_answers",
                        to="puzzle_editing.puzzle",
                    ),
                ),
            ],
            options={
                "ordering": ["puzzle", "answer"],
                "unique_together": {("puzzle", "answer")},
            },
        ),
    ]
