# Generated by Django 4.2.2 on 2023-06-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("puzzle_editing", "0025_testsolveguess_partial_response_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testsolveparticipation",
            name="aspects_accessibility",
        ),
        migrations.RemoveField(
            model_name="testsolveparticipation",
            name="aspects_enjoyable",
        ),
        migrations.RemoveField(
            model_name="testsolveparticipation",
            name="aspects_unenjoyable",
        ),
        migrations.RemoveField(
            model_name="testsolveparticipation",
            name="clues_needed",
        ),
        migrations.RemoveField(
            model_name="testsolveparticipation",
            name="errors_found",
        ),
        migrations.RemoveField(
            model_name="testsolveparticipation",
            name="flavortext_feedback",
        ),
        migrations.RemoveField(
            model_name="testsolveparticipation",
            name="flavortext_overall",
        ),
        migrations.RemoveField(
            model_name="testsolveparticipation",
            name="general_feedback",
        ),
        migrations.RemoveField(
            model_name="testsolveparticipation",
            name="instructions_feedback",
        ),
        migrations.RemoveField(
            model_name="testsolveparticipation",
            name="instructions_overall",
        ),
        migrations.RemoveField(
            model_name="testsolveparticipation",
            name="misc_feedback",
        ),
        migrations.RemoveField(
            model_name="testsolveparticipation",
            name="solve_path",
        ),
        migrations.RemoveField(
            model_name="testsolveparticipation",
            name="stuck_overall",
        ),
        migrations.RemoveField(
            model_name="testsolveparticipation",
            name="stuck_points",
        ),
        migrations.RemoveField(
            model_name="testsolveparticipation",
            name="stuck_time",
        ),
        migrations.RemoveField(
            model_name="testsolveparticipation",
            name="stuck_unstuck",
        ),
        migrations.RemoveField(
            model_name="testsolveparticipation",
            name="suggestions_change",
        ),
        migrations.RemoveField(
            model_name="testsolveparticipation",
            name="suggestions_keep",
        ),
        migrations.RemoveField(
            model_name="testsolveparticipation",
            name="technical_issues",
        ),
        migrations.RemoveField(
            model_name="testsolveparticipation",
            name="technical_issues_description",
        ),
        migrations.RemoveField(
            model_name="testsolveparticipation",
            name="technical_issues_device",
        ),
        migrations.AddField(
            model_name="testsolvefeedback",
            name="meta_info",
            field=models.TextField(
                blank=True,
                help_text=(
                    "**Meta info**. Did you use any information that wouldn't be"
                    " available to solvers? For example, knowing the answer from a"
                    " meta, knowing the meta mechanism, knowing the author, being"
                    " spoiled on something, etc."
                ),
            ),
        ),
    ]
