# Generated by Django 5.0.2 on 2024-03-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzle_editing", "0025_add_closed_testsolving"),
    ]

    operations = [
        migrations.AddField(
            model_name="testsolveparticipation",
            name="in_discord_thread",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="testsolveparticipation",
            name="in_discord_thread",
            field=models.BooleanField(default=False),
        ),
    ]
