# Generated by Django 5.0.2 on 2024-03-19 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_editing', '0026_testsolve_participation_in_discord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testsolvesession',
            options={'permissions': (('close_session', 'Can close a session at any point'),)},
        ),
    ]
