# Generated by Django 4.2.2 on 2023-06-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "puzzle_editing",
            "0026_remove_testsolveparticipation_aspects_accessibility_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="hint",
            name="description",
            field=models.CharField(
                default="",
                help_text=(
                    'A description of when this hint should apply; e.g. "The solvers'
                    " have not yet figured out that the mirrors represent word"
                    ' transformations"'
                ),
                max_length=1000,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="puzzle",
            name="deep",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="puzzle",
            name="deep_key",
            field=models.CharField(blank=True, max_length=500, verbose_name="DEEP key"),
        ),
        migrations.AddField(
            model_name="puzzle",
            name="discord_emoji",
            field=models.CharField(
                default=":question:",
                help_text=(
                    "The emoji that'll be used in Discord notifications. Please leave"
                    " in string form, e.g. :question:."
                ),
                max_length=50,
            ),
        ),
    ]
