# Generated by Django 5.0.4 on 2024-05-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzle_editing", "0027_alter_testsolvesession_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("NO", "No need"),
                    ("REQ", "Requested"),
                    ("APP", "Triaged, waiting on team"),
                    ("BLOK", "Triaged, waiting on puzzle"),
                    ("COMP", "Completed"),
                    ("X", "Cancelled"),
                ],
                default="REQ",
                max_length=4,
            ),
        ),
    ]
