# Generated by Django 4.2.2 on 2023-06-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "puzzle_editing",
            "0027_hint_description_puzzle_deep_puzzle_deep_key_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="puzzlepostprod",
            name="authors",
        ),
        migrations.RemoveField(
            model_name="puzzlepostprod",
            name="complicated_deploy",
        ),
        migrations.RemoveField(
            model_name="puzzlepostprod",
            name="zip_file",
        ),
        migrations.AddField(
            model_name="puzzlepostprod",
            name="host_url",
            field=models.CharField(
                blank=True,
                help_text=(
                    "The base URL where this puzzle is postprodded. Defaults to staging"
                ),
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="puzzle_template",
            field=models.CharField(
                blank=True,
                help_text="Path to puzzle template in the hunt repo for autopostprod",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="solution_template",
            field=models.CharField(
                blank=True,
                help_text="Path to sol template in the hunt repo for autopostprod",
                max_length=500,
            ),
        ),
    ]
