# Generated by Django 4.2.2 on 2023-06-18 20:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("puzzle_editing", "0028_remove_puzzlepostprod_authors_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="hint",
            unique_together={("puzzle", "description")},
        ),
    ]
