# Generated by Django 5.0.4 on 2024-05-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzle_editing", "0028_rename_support_request_statuses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportrequest",
            name="team",
            field=models.CharField(
                choices=[
                    ("ART", "🎨 Art"),
                    ("ACC", "🔎 Accessibility"),
                    ("FAB", "🔨 Fabrication"),
                    ("OPS", "🚧 Operations"),
                    ("TECH", "👩🏽\u200d💻 Tech"),
                ],
                max_length=4,
            ),
        ),
    ]
