# Generated by Django 5.0.4 on 2024-05-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzle_editing", "0029_add_fabrication_lead"),
    ]

    operations = [
        migrations.AddField(
            model_name="testsolvesession",
            name="late_testsolve",
            field=models.BooleanField(
                default=False,
                help_text="Whether this testsolve occurred after the puzzle had passed testsolving",
            ),
        ),
    ]
