# Generated by Django 4.2.2 on 2023-07-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("puzzle_editing", "0030_alter_puzzle_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="puzzle",
            name="discord_emoji",
            field=models.CharField(
                default=":question:",
                max_length=100,
                help_text=(
                    "The emoji that'll be used in Discord notifications. Please leave"
                    " in string form, e.g. `:question:`. You can use multiple emojis if"
                    " necessary, but try to keep it to 1 (and no more than 2)."
                ),
            ),
        ),
    ]
