# Generated by Django 5.1.1 on 2024-10-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzle_editing", "0031_change_hint_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="puzzle",
            name="status",
            field=models.CharField(
                choices=[
                    ("II", "Initial Idea"),
                    ("ID", "In Development"),
                    ("AA", "Waiting for Answer"),
                    ("W", "Writing / Revising (Answer Assigned)"),
                    ("WF", "Writing / Revising (Answer Flexible)"),
                    ("T", "In Testsolving"),
                    ("NS", "Finalizing Solution"),
                    ("AF", "Puzzle Written, Waiting for Round"),
                    ("AM", "Awaiting Manufacturing"),
                    ("NP", "Ready for Postprodding"),
                    ("AP", "Awaiting Approval After Postprod"),
                    ("NF", "Factchecking"),
                    ("NR", "Final Revisions"),
                    ("NK", "Needs Final Day Factcheck"),
                    ("D", "Done"),
                    ("DF", "Deferred"),
                    ("X", "Dead"),
                ],
                default="II",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="puzzlecomment",
            name="status_change",
            field=models.CharField(
                blank=True,
                choices=[
                    ("II", "Initial Idea"),
                    ("ID", "In Development"),
                    ("AA", "Waiting for Answer"),
                    ("W", "Writing / Revising (Answer Assigned)"),
                    ("WF", "Writing / Revising (Answer Flexible)"),
                    ("T", "In Testsolving"),
                    ("NS", "Finalizing Solution"),
                    ("AF", "Puzzle Written, Waiting for Round"),
                    ("AM", "Awaiting Manufacturing"),
                    ("NP", "Ready for Postprodding"),
                    ("AP", "Awaiting Approval After Postprod"),
                    ("NF", "Factchecking"),
                    ("NR", "Final Revisions"),
                    ("NK", "Needs Final Day Factcheck"),
                    ("D", "Done"),
                    ("DF", "Deferred"),
                    ("X", "Dead"),
                ],
                help_text="Any status change caused by this comment. Only used for recording history and computing statistics; not a source of truth (i.e. the puzzle will still store its current status, and this field's value on any comment doesn't directly imply anything about that in any technically enforced way).",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="statussubscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("II", "Initial Idea"),
                    ("ID", "In Development"),
                    ("AA", "Waiting for Answer"),
                    ("W", "Writing / Revising (Answer Assigned)"),
                    ("WF", "Writing / Revising (Answer Flexible)"),
                    ("T", "In Testsolving"),
                    ("NS", "Finalizing Solution"),
                    ("AF", "Puzzle Written, Waiting for Round"),
                    ("AM", "Awaiting Manufacturing"),
                    ("NP", "Ready for Postprodding"),
                    ("AP", "Awaiting Approval After Postprod"),
                    ("NF", "Factchecking"),
                    ("NR", "Final Revisions"),
                    ("NK", "Needs Final Day Factcheck"),
                    ("D", "Done"),
                    ("DF", "Deferred"),
                    ("X", "Dead"),
                ],
                max_length=2,
            ),
        ),
    ]
