# Generated by Django 4.2.2 on 2023-07-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("puzzle_editing", "0031_alter_puzzle_discord_emoji"),
    ]

    operations = [
        migrations.AlterField(
            model_name="puzzle",
            name="discord_emoji",
            field=models.CharField(
                default=":question:",
                help_text=(
                    "The emoji that'll be used in Discord notifications. Please leave"
                    " in string form, e.g. `:question:`. You can use multiple emojis if"
                    " necessary (e.g. `:question::question`), but try to keep it to 1"
                    " (and no more than 2)."
                ),
            ),
        ),
    ]
