# Generated by Django 5.1.1 on 2024-10-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzle_editing", "0032_new_awaiting_manufacturing_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="puzzle",
            name="logistics_factcheck_notes",
            field=models.TextField(
                blank=True,
                help_text="Any special notes for factchecking about this puzzle.",
            ),
        ),
    ]
