# Generated by Django 4.2.2 on 2023-07-05 23:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("puzzle_editing", "0033_alter_puzzle_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportrequest",
            name="assignees",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_support_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
