# Generated by Django 5.1.4 on 2024-12-31 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzle_editing", "0033_add_factcheck_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="puzzlecredit",
            name="credit_type",
            field=models.CharField(
                choices=[
                    ("ART", "Art"),
                    ("TCH", "Tech"),
                    ("FAB", "Fabrication"),
                    ("OTH", "Other"),
                ],
                default="ART",
                max_length=3,
            ),
        ),
    ]
