# Generated by Django 4.2.2 on 2023-07-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("puzzle_editing", "0034_supportrequest_assignees"),
    ]

    operations = [
        migrations.AddField(
            model_name="puzzle",
            name="postprod_issue_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="github_username",
            field=models.CharField(blank=True, max_length=39),
        ),
    ]
