# Generated by Django 4.2.2 on 2023-07-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("puzzle_editing", "0035_puzzle_postprod_issue_id_user_github_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testsolvefeedback",
            name="meta_info",
            field=models.TextField(
                blank=True,
                help_text=(
                    "**Meta info**. Did you use any information that wouldn't normally"
                    " be available to solvers? For example, knowing the answer from the"
                    " meta, knowing the meta mechanism or constraints, knowing the"
                    " author, being spoiled on something, receiving nudges, new drafts,"
                    " etc."
                ),
            ),
        ),
    ]
