# Generated by Django 4.2.2 on 2023-08-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("puzzle_editing", "0036_alter_testsolvefeedback_meta_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="puzzle",
            name="editor_notes",
            field=models.TextField(
                blank=True,
                help_text="A **succinct, spoilery list** of mechanics and themes used.",
                verbose_name="Mechanics",
            ),
        ),
    ]
