# Generated by Django 4.2.4 on 2023-08-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("puzzle_editing", "0037_alter_puzzle_editor_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="pseudoanswer",
            name="case_sensitive",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Whether or not this pseudoanswer needs to be submitted with the"
                    " correct casing."
                ),
            ),
        ),
        migrations.AddField(
            model_name="pseudoanswer",
            name="special_sensitive",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Whether or not this pseudoanswer shouldn't ignore special"
                    " characters."
                ),
            ),
        ),
        migrations.AddField(
            model_name="pseudoanswer",
            name="whitespace_sensitive",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Whether or not this pseudoanswer shouldn't ignore whitespaces."
                ),
            ),
        ),
    ]
