# Generated by Django 4.2.2 on 2023-08-20 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("puzzle_editing", "0038_pseudoanswer_case_sensitive_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportrequest",
            name="puzzle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="support_requests",
                to="puzzle_editing.puzzle",
            ),
        ),
    ]
