# Generated by Django 4.2.5 on 2023-11-10 15:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("puzzle_editing", "0039_alter_supportrequest_puzzle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="puzzlepostprod",
            name="slug",
            field=models.CharField(
                help_text=(
                    "The part of the URL on the hunt site referrring to this puzzle."
                    " E.g. for https://puzzle.hunt/puzzle/fifty-fifty, this would be"
                    " 'fifty-fifty'."
                ),
                max_length=200,
                validators=[
                    django.core.validators.RegexValidator(
                        regex="[^<>#%\"\\'|{})(\\[\\]\\/\\\\\\^?=`;@&, ]{1,200}"
                    )
                ],
            ),
        ),
    ]
